.buildkite/pipeline.yaml

No need to run on private builders now that the repo is public.

ci: change Buildkite agent tags

---

.buildkite/public-cache-push.yaml

Note: this is configured (in Buildkite) only to run on pushes to
`main`, so PR build artifacts will not be present in our public Cachix
cache, on purpose.
Closes #942

ci: add a Buildkite job to push to our public Cachix cache

---

flake.nix

Closes https://github.com/hackworthltd/primer/issues/1013
These files don't contribute to a Cabal build or Haskell-related
check, so we don't want changes to them to trigger extraneous Nix
builds.

chore: add more files to Haskell source filter

---

flake.nix

This is just some Nix convenience, no functional changes here.

chore(nix): add `primer-client` to the flake's apps

---

flake.nix
nix/pkgs/benchmarks/default.nix

We never use these, and they require an otherwise completely redundant
benchmark run, which takes a fair amount of time.
Note that I tried to use `criterion-report` to generate the HTML
results from the Criterion JSON run output, but it doesn't work for
some reason:
```
./result/bin/criterion-report report /nix/store/6rd2xgrrv1lrziad8jlla68r5rd9c2sd-primer-benchmark-results-json/results.json results.html --template json
Error reading file: /nix/store/6rd2xgrrv1lrziad8jlla68r5rd9c2sd-primer-benchmark-results-json/results.json
"Error in $: cannot unpack array of length 10 into a tuple of length 3"
```

ci: drop Criterion HTML results

---

primer-service/primer-service.cabal
primer/primer.cabal

Fixes an issue where Hedgehog sometimes fails to replay correctly in the presence of discards, particularly in our `tasty_available_actions_accepted` test: https://github.com/hedgehogqa/haskell-hedgehog/issues/487.

fix: Downgrade Hedgehog to version 1.1

---

primer/src/Primer/Typecheck.hs
primer/test/Tests/Action/Available.hs

Consider (some sort of) a `let` in a checkable position, whose body is
synthesisable, e.g. `(λx. let y = ... in xor x y) : Bool -> Bool`. Prior to
this commit, our treatment of metadata between `let` and `letrec` was
inconsistent:
- they both treat the body `xor x y` the same: checking it against
`Bool`, finding it is synthesises `Bool` and then giving it a `TCEmb`
metadata.
- a `let` node would then get the same metadata
- a `letrec` node would only get `TCChkedAt` metadata
This is visible to a consumer of our API: what actions we offer differ,
see the added test.

fix: letrec metadata

---

primer/src/Primer/Action.hs
primer/src/Primer/Action/Available.hs
primer/test/Tests/Action/Available.hs
primer/test/outputs/available-actions/M.comprehensive/Beginner-Editable.fragment
primer/test/outputs/available-actions/M.comprehensive/Expert-Editable.fragment
primer/test/outputs/available-actions/M.comprehensive/Intermediate-Editable.fragment

We fix what names are offered for `let`s and `forall`s, and add tests for each available action which offers names (except for type lets and renaming pattern variables, which are hard to test for technical reasons).

fix: offered names

---

primer/gen/Primer/Gen/Core/Typed.hs
primer/src/Primer/App.hs
primer/src/Primer/Core.hs
primer/src/Primer/Typecheck.hs
primer/test/Tests/Action.hs
primer/test/Tests/Action/Available.hs
primer/test/Tests/Action/Prog.hs
primer/test/Tests/Typecheck.hs

Currently they must synthesise some type (and we don't care what), but there is no particular reason for this that I can recall, other than following Hazel. I think it may be nicer UX if we change this.
In particular, with checkable saturated constructors we would then be able to write a constructor directly inside a hole, without having to annotate it. Even without that, we could write a lambda directly inside a hole (currently it would need an annotation): `{? λx.t[x] ?}` would be valid, and synthesise a hole exactly when we have that `x : ? ⊢ ? ∋ t[x]`.
Essentially, whenever we now write `{? t : ? ?}`, we could drop the annotation. Whenever we currently have a more-specific annotation (currently this is only possible when a human explicitly writes it, I think), then we could still …

feat!: Innards of non-empty holes should check against hole type

---

flake.lock
flake.nix

HLS 2.0.0.0 is out, let's try again.

chore: build HLS from haskell.nix again

---

primer/gen/Primer/Gen/Core/Typed.hs

The generators and the typechecker disagreed about typing rules of consttructors which themselves are checked against a hole type. For example, in `? ∋ MkPair s t`, the typechecker would check that `? ∋ s` and `? ∋ t`, whereas the generator would pick two arbitrary types (of kind `KType`) `A` and `B` and generate arguments `s` and `t` such that `A ∋ s` and `B ∋ t`. This disagreement results in (rare) test failures of `tasty_synth_well_typed_extcxt` etc.
An (slightly simplified) example of a failure is:
- `tasty_synth_well_typed_extcxt` calls `genSyn`
- the generator attempts to generate something of type `?`
- it decides to use a constructor `MkPair`, and since we are working at a hole type, it wants to generate two arguments of arbitrary types.
- it decides to generate the first argument …

fix: generate well-typed terms with saturated constructors

---

primer-rel8/primer-rel8.cabal
primer-rel8/src/Primer/Database/Rel8/Rel8Db.hs
primer-rel8/test/Tests/FindSessions.hs
primer-rel8/testlib/Primer/Database/Rel8/Test/Util.hs
primer-selda/primer-selda.cabal
primer-selda/src/Primer/Database/Selda.hs
primer-selda/src/Primer/Database/Selda/SQLite.hs
primer-selda/test/Tests/FindSessions.hs
primer-selda/testlib/Primer/Database/Selda/Test/Util.hs
primer-service/src/Primer/Client.hs
primer-service/src/Primer/Servant/Types.hs
primer-service/src/Primer/Server.hs
primer-service/test/outputs/OpenAPI/openapi.json
primer/src/Primer/API.hs
primer/src/Primer/Database.hs
primer/test/Tests/API.hs
primer/test/Tests/Database.hs
primer/test/Tests/NullDb.hs

Apologies for the large first commit. There was no reasonable way to break it up into smaller pieces. Most of it is tests and refactoring, at least.
*edit*: note to future readers, we ended up making this implementation case-*in*sensitive only, at least for now. When time allows, we'll implement case-sensitive search. See https://github.com/hackworthltd/primer/pull/1033#issuecomment-1562089557 for the motivation.

feat!: search the database by session name

---

nix/pkgs/scripts/primer-service-entrypoint.sh
primer-service/exe-server/Main.hs
primer-service/src/Primer/Server.hs

With this change, we can now serve cross-origin requests for Primer
resources from behind an authentication proxy (or similar). Prior to
this change, we could not, because `Access-Control-Allow-Origin` was
always returned as `*`, and no legitimate browser will send
cross-origin cookies or auth-related headers in that case.
By default, the CORS behavior of `primer-service` is the same as
before:
* The server replies with `Access-Control-Allow-Origin: *`.
* The server does not set the `Vary: Origin` header.
* The server does not require that the client set the `Origin:`
header.
However, when `primer-service` is invoked with the
`--cors-allow-origin` flag (or the `CORS_ALLOW_ORIGIN` environment
variable is passed to the Docker container), the operator can now
specify explicit allowed …

feat: add support for explicit CORS origins

---

primer/src/Primer/API.hs
primer/src/Primer/App.hs
primer/src/Primer/Builtins.hs
primer/src/Primer/Subst.hs
primer/src/Primer/Typecheck.hs
primer/src/Primer/Typecheck/TypeError.hs
primer/test/Tests/Action/Available.hs

Per the terminology we've been using since the project's inception.
We've done a good job with this overall, we've just missed a
few. (Note that there are still a few occurrences of "user" in the
code base and project documentation, but those uses don't refer to
people who're using Primer, which is the use case we care about.)

chore: change occurrences of "user" -> "student"

---

primer-service/exe-server/Main.hs
primer-service/src/Primer/OpenAPI.hs
primer-service/src/Primer/Server.hs
primer-service/test/Tests/OpenAPI.hs
primer-service/test/outputs/OpenAPI/openapi.json
primer/src/Foreword.hs
primer/src/Primer/API.hs
primer/src/Primer/Action.hs
primer/src/Primer/Action/Available.hs
primer/src/Primer/Action/Errors.hs
primer/src/Primer/Action/Priorities.hs
primer/src/Primer/Action/ProgAction.hs
primer/src/Primer/Action/ProgError.hs
primer/src/Primer/App.hs
primer/src/Primer/App/Base.hs
primer/src/Primer/Core/Meta.hs
primer/src/Primer/JSON.hs
primer/src/Primer/Module.hs
primer/src/Primer/Questions.hs
primer/src/Primer/TypeDef.hs
primer/src/Primer/Typecheck/Cxt.hs
primer/src/Primer/Zipper.hs
primer/test/Tests/Action/Available.hs
primer/test/Tests/Action/Prog.hs
primer/test/Tests/Serialization.hs
primer/test/Tests/Typecheck.hs
primer/test/outputs/serialization/edit_response_2.json
primer/test/outputs/serialization/prog.json
primer/test/outputs/serialization/selection.json

This allows us to finally take advantage of #367 (with the caveats detailed in #399, #401 and #402).
This will ultimately enable us to render typedefs alongside terms in our frontend, and modify them using the same actions panel with which we manipulate terms.
See #1040 and #1041 for potential follow-ups.

feat: Expose typedef edit actions in OpenAPI

---

primer/gen/Primer/Gen/Core/Typed.hs
primer/test/Tests/Action/Available.hs

We already did this for `genName`.
Signed-off-by: Ben Price <ben@hackworthltd.com>

test: adjust distributions to make duplicates more likely

---

primer-service/exe-server/Main.hs
primer-service/src/Primer/OpenAPI.hs
primer-service/src/Primer/Servant/OpenAPI.hs
primer-service/src/Primer/Server.hs
primer-service/test/Tests/OpenAPI.hs
primer-service/test/outputs/OpenAPI/openapi.json
primer/src/Primer/API.hs
primer/src/Primer/API/NodeFlavor.hs
primer/src/Primer/Action/ProgError.hs

This is a rebase/rewrite of #1050

feat: expose type of current selection via OpenAPI

---

primer-service/src/Primer/Servant/OpenAPI.hs
primer-service/test/outputs/OpenAPI/openapi.json

Though this method is technically a `GET`, we've found that OpenAPI
clients often don't support complex bodies in `GET` methods, and this
one requires that we pass a `Selection`. So, just as with the
`getAvailableActions` OpenAPI endpoint, we make `getTypeOrKind` a faux
`POST`.

fix: change `getTypeOrKind` OpenAPI endpoint from `GET` to `POST`

---

primer/src/Primer/API.hs

This fixes an issue when using this functionality in our frontend to display the type of the currently-selected node: the fallback `trivialTree` was displayed for nodes in checkable positions (lambdas, constructors).
@brprice would be better placed than I am to explain why we originally ignored this part of the typecache in #1050, or whether this is quite the right approach. But in his absence, and with the Zurihac push, I'd suggest we merge this anyway. I doubt there are any serious downsides.

fix: Output checked type in `getSelectionTypeOrKind` if none is synthed

---

primer-service/test/Tests/OpenAPI.hs
primer-service/test/outputs/OpenAPI/openapi.json
primer/src/Primer/API.hs
primer/test/Tests/API.hs

Note that, out of a need for expediency, there are currently not any
unit tests for the new scenario, but it's a trivial change.
BREAKING CHANGE: this adds a parameter to the `newSession` and
`createSession` APIs.

feat!: support creating new sessions without importing the Prelude

---

primer/src/Primer/Action/Available.hs
primer/src/Primer/Typecheck.hs
primer/src/Primer/Typecheck/Utils.hs
primer/test/outputs/available-actions/M.comprehensive/Beginner-Editable.fragment
primer/test/outputs/available-actions/M.comprehensive/Expert-Editable.fragment
primer/test/outputs/available-actions/M.comprehensive/Intermediate-Editable.fragment

This is an extension of https://github.com/hackworthltd/primer/pull/1045, which itself was a proof of concept/best effort to annotate variables that match the type of a hole up to alpha. Here we extend this feature to non-primitive value constructors.
This implementation uses `valConType` to extract the value constructor's type. For the record, the documentation for `conInfo`, which also uses `valConType`, reads as follows:
> the type an eta-expanded version of this constructor would check against e.g. `Cons`'s "type" is `∀a. a -> List a -> List a`.

feat: annotate offered valcons that match the selection's type

---

primer/src/Primer/API.hs

For embeddings, (i.e. where we have both a checked-at and synthesised type), we must (with the current API design) choose one type to report as the type of the selection. Previously we chose the synthed, but we now:
- if exactly one is a hole, then choose the other
- otherwise, chose the synthed (As future work, we may want to change the api to report both types, or maybe "merge" the two types. However, it is not clear what the correct design is here. (Note that "merging" is somewhat awkward due to binders and needing to worry about alpha equivalence).)
Note that these two types must be consistent. Consider the situation where we are checking `T ∋ e` and discover that `e ∈ S`. If we did not have `T ~ S`, then this would be a type error, which smartholes would rectify by putting `e` in a …

feat: report better types in API for embeddings

---

.github/workflows/push-to-ghcr.yaml

In other words, add `workflow_dispatch` to
`.github/workflows/push-to-ghcr.yaml`.

ci: add the ability to push any `primer-service` branch to ghcr.io

---

primer-service/src/Primer/Servant/OpenAPI.hs
primer-service/test/outputs/OpenAPI/openapi.json

It's unfortunate that this is baked into the OpenAPI spec file. What we should probably do is bump it to something much larger than we could feasibly want (for now), and then provide a command-line setting to the server which will provide the real limit, only at runtime.

chore: bump eval step limit in the OpenAPI to 300 steps

---

flake.lock
flake.nix

Also:
* Unpin `haskell.nix`
* Build HLS from `haskell.nix` again, with a small workaround

chore(nix): bump dependencies

---

flake.nix
primer/src/Primer/Typecheck.hs

Now that cborg (which is a dependency of weeder) works again for aarch64 (https://github.com/well-typed/cborg/pull/307), we can reenable this check.
We also remove one weed which has grown in the period when weeder was disabled.

chore: enable weeder, remove a weed

---

bugreport.sh

In a linked worktree, `.git` is a regular file, whose contents records the location of the main worktree.

fix: bugreport.sh support for git worktrees

---

primer/src/Primer/API.hs
primer/src/Primer/Action.hs
primer/src/Primer/Action/Available.hs
primer/src/Primer/Action/Errors.hs
primer/src/Primer/Action/ProgError.hs
primer/src/Primer/App.hs
primer/src/Primer/App/Utils.hs
primer/src/Primer/Typecheck.hs
primer/test/Tests/Action/Available.hs
primer/test/Tests/Action/Prog.hs

This was originally intended to be a part of #949, but the sheer number of issues revealed by the property test meant it was worth splitting out. Especially as the bugs are actually from much earlier work in adding the core `ProgAction`s for editing typedefs, rather than the higher-level API-related work in #949. Also, this branch might now be taken over by @brprice (though I'd be happy to clean things up a little before handing over, or at least walk through on a video call), since the remaining fixes (see final commit) are more in his wheelhouse.
We may wish to document the fixes better by adding a regression test for each, and/or adding hedgehog replay seeds to the commit messages. I was unable to do this originally since the version of Hedgehog we were using had replay issues (#1027). …

fix: extend available actions property test to cover typedefs, and fix revealed bugs

---

primer-api/src/Primer/API.hs
primer/src/Primer/Action/ProgError.hs

This is something that I think @brprice pointed out while we were practising for the Zurihac demo.

Fix `getSelectionTypeOrKind` for constructor fields

---

primer/src/Primer/Core/Meta.hs

This one-character change massively reduces our memory usage (measured by maximum residency) on some workloads.  When running the testsuite with `--hedgehog-tests 0` (to get reproducible results) we see a (roughly) 15% drop in maximum residency (as measured by `+RTS -s`), and with the following patch to run a much bigger version of `EvalFull.unit_8`, we see a 97% drop, and the total memory in use drops from 1177MB to 58MB! It also has a small beneficial effect on the amount of memory copied during GC, and a negligible effect on both total memory allocated and elapsed runtimes.
```
diff --git a/primer/test/Tests/EvalFull.hs b/primer/test/Tests/EvalFull.hs index c98878049..9292b2870 100644
--- a/primer/test/Tests/EvalFull.hs
+++ b/primer/test/Tests/EvalFull.hs
@@ -209,13 +209,13 @@ unit_7 = …
```

perf: strictify Meta's ID field

---

cabal.project
primer-api/primer-api.cabal
primer-service/primer-service.cabal
primer/primer.cabal
primer/test/Tests/Action/Available.hs
primer/test/Tests/Eval/Utils.hs
primer/test/Tests/Questions.hs

Now that Hedgehog 1.4 has been released with [the fix for replaying tests](https://github.com/hedgehogqa/haskell-hedgehog/pull/489), we can migrate off 1.1. This is a prerequisite for upgrading ghc to 9.6 (#1077).
Note that currently we need to `allow-newer` to get hedgehog-classes to work with hedgehog 1.4; I have opened an upstream PR at https://github.com/hedgehogqa/haskell-hedgehog-classes/pull/52

chore: upgrade Hedgehog to version 1.4

---

flake.nix

This is required for `kubectl cp`, which is potentially useful for getting databases into and out of the pod.

chore: add `gnutar` to the Docker container

---

primer-benchmark/src/Benchmarks.hs
primer/primer.cabal
primer/src/Primer/App.hs
primer/src/Primer/Eval.hs
primer/src/Primer/Eval/Detail.hs
primer/src/Primer/Eval/Let.hs
primer/src/Primer/Eval/NormalOrder.hs
primer/src/Primer/Eval/Push.hs
primer/src/Primer/Eval/Redex.hs
primer/src/Primer/EvalFull.hs
primer/src/Primer/Zipper/Type.hs
primer/test/Tests/Eval.hs
primer/test/Tests/EvalFull.hs
primer/test/Tests/Prelude/Integer.hs
primer/test/Tests/Prelude/Polymorphism.hs
primer/test/Tests/Prelude/Utils.hs

This addresses #44 
Notes for reviewers: I suggest going commit-by-commit, but first have a look at my comments-on-code below, some of which have come detached from the code (and thus won't show up in the commit-by-commit review) due to a rebase.

feat: push down lets

---

primer-api/src/Primer/API.hs
primer-api/test/Tests/API.hs
primer-benchmark/src/Benchmarks.hs
primer-service/src/Primer/OpenAPI.hs
primer-service/src/Primer/Servant/OpenAPI.hs
primer-service/test/outputs/OpenAPI/openapi.json
primer/src/Primer/App.hs
primer/src/Primer/Eval.hs
primer/src/Primer/Eval/NormalOrder.hs
primer/src/Primer/EvalFull.hs
primer/test/Tests/Eval/Utils.hs
primer/test/Tests/EvalFull.hs
primer/test/Tests/Prelude/Utils.hs
primer/test/Tests/Undo.hs

This change means our EvalFull is "closed evaluation", rather than "open evaluation". The main reason to do this is so that evaluations of programs-in-construction (especially recursive ones) do not pointlessly blow up in size: if `even` and `odd` are defined recursively, then evaluating `even`  would evaluate under the lambda and inside case branches, expanding `odd` and recursing; when it eventually times out one would have a big tree with many unrolled copies of `even` and `odd`, which is not very illuminating. 
Note that we do not evaluate in the RHS of pattern match branches which bind variables, for the same reason as we do not evaluate under lambdas; for consistency we also do not evaluate in the RHS of branches which do not bind variables.

feat: optionally do not evaluate under binders (except lets)

---

primer/src/Primer/Primitives.hs
primer/src/Primer/Primitives/PrimDef.hs
primer/test/Tests/EvalFull.hs

Closes #1118.
Note that while this test captures the key property (that primitives can be lazy in an argument), we haven't implemented all suggestions in https://github.com/hackworthltd/primer/issues/1118#issuecomment-1689685996, for reasons outlined in the commit message.

test: Primitive functions can exhibit laziness

---

primer/src/Primer/Primitives.hs
primer/test/Tests/EvalFull.hs

Since `const x y` is synthesisable but `x` is checkable, the reduction rule is `const x y ~> x : Bool` (rather than `const x y ~> x`). Note that `const` is restricted to type `Bool -> Int -> Bool`, and that this reduction matches that of obvious analogue where `const` is replaced by the non-primitive `(λx y. x) : Bool -> Int -> Bool`.

fix: const primitive directionality

---

primer-api/src/Primer/API.hs
primer-api/test/Tests/Database.hs
primer-selda/src/Primer/Database/Selda/SQLite.hs
primer/src/Primer/App.hs
primer/src/Primer/Database.hs
primer/test/Tests/Database.hs

We're now on GHC 9.6.3, so these should no longer be necessary on our
build.
Closes https://github.com/hackworthltd/primer/issues/1152

chore: remove GHC 9.6.2 spurious warning workarounds

---

primer-benchmark/src/Benchmarks.hs
primer/gen/Primer/Gen/Core/Raw.hs
primer/gen/Primer/Gen/Core/Typed.hs
primer/primer.cabal
primer/src/Primer/App.hs
primer/src/Primer/Core/Transform.hs
primer/src/Primer/Eval.hs
primer/src/Primer/Eval/Redex.hs
primer/src/Primer/Typecheck.hs
primer/src/Primer/Typecheck/TypeError.hs
primer/src/Primer/Zipper.hs
primer/test/Tests/Action/Available.hs
primer/test/Tests/Eval.hs
primer/test/Tests/EvalFull.hs
primer/test/Tests/Prelude/Utils.hs
primer/test/Tests/Shadowing.hs
primer/test/Tests/Typecheck.hs
primer/test/Tests/Zipper.hs
primer/test/outputs/available-actions/M.comprehensive/Expert-Editable.fragment

Both "construction" api calls and evaluation will not introduce shadowing into a program which currently contains none, except in a few specific cases:
- evaluation under a binder in one of two situations (both "inline a global which has a binder of the same name as a local one")
- inline a global variable, e.g. `λx. foo` reduces to `λx. λx.t` where `foo = λx.t`
(note that we don't have the same problem for local `let f = λx.t in λx.s` as we will notice the shadowing issue when considering pushing the `let` under the lambda and do an initial renaming step `let f = λx.t in λy.let x=y in t`)
- case-of-known-constructor, which "inlines" parts of the type definition: `Λα. case C t : T of C x -> s` reduces to `Λα. let x = t : ∀α.A in s` when we have `data T = C (∀α.A)`
- actions
- anything …

Ensure API calls do not introduce shadowing

---

primer-api/src/Primer/API/NodeFlavor.hs

It looks like this was mistakenly copied from `primer/src/Primer/Action/Errors.hs`.

chore: Remove stray comment about `NodeFlavor` being split

---

primer-api/src/Primer/API.hs
primer-api/test/Tests/API.hs
primer-service/src/Primer/OpenAPI.hs
primer-service/test/Tests/OpenAPI.hs
primer-service/test/outputs/OpenAPI/openapi.json
primer/src/Primer/Typecheck/Kindcheck.hs

For non-empty holes (aka "mismatches"), the OpenAPI now gives both the expected and actual types. We also record the checked-at kind of non-empty type holes in the metadata rather than the synthesised one, for consistency with the term level.
BREAKING CHANGE: this changes the OpenAPI schema.

feat!: API gives more details on mismatched types

---

primer-api/primer-api.cabal
primer-api/test/Tests/API.hs
primer-selda/primer-selda.cabal
primer-selda/src/Primer/Database/Selda/SQLite.hs
primer-selda/testlib/Primer/Database/Selda/Test/Util.hs
primer-service/primer-service.cabal
primer-service/test/Tests/OpenAPI.hs
primer/primer.cabal
primer/src/Primer/Database.hs
primer/src/Primer/UUIDv4.hs
primer/test/Tests/NullDb.hs

`uuid` drags in `network-info`, which doesn't build on GHC's Wasm target. The only drawback to `uuid-types` for our purposes is that it doesn't include a cryptographically secure generator for UUIDv4, which we've been using up until now (specifically, the `nextRandom` effect).
Therefore, we replace `nextRandom` with our own pseudo-random implementation. Note that our implementation is *not* cryptographically secure, as `entropy` does not build on the Wasm target, either.

chore: switch from `uuid` to `uuid-types`

---

flake.nix
primer-service/primer-service.cabal

This matches the naming scheme used by all other components in the project.

fix: Add `primer-` prefix to service test suite

---

primer/src/Primer/Primitives.hs

Previously, they were transparent unless an explicit color was set, which could be confusing, particularly since we opted not to show outlines.

fix: Default to black fill color for shapes in animations

---

primer/src/Primer/Action/Available.hs
primer/src/Primer/Action/ProgError.hs
primer/src/Primer/App.hs
primer/src/Primer/Def/Utils.hs
primer/test/Tests/Action/Available.hs
primer/test/Tests/Action/Prog.hs

For consistency with https://github.com/hackworthltd/primer/pull/1153, as anticipated in https://github.com/hackworthltd/primer/issues/1133#issuecomment-1715843100.
The only context in which we still ban edits rather than fixing up use sites is for type definition parameters, as tracked in https://github.com/hackworthltd/primer/issues/402.

Allow deleting an in-use term definition

---

.buildkite/primer-wasm.yaml
Makefile
cabal.project
docs/development-guide-toc.md
docs/wasm.md
flake.lock
flake.nix
primer-api/.gitignore
primer-api/Makefile
primer-api/primer-api.cabal
primer-selda/primer-selda.cabal
primer-service/src/Primer/OpenAPI.hs
primer/.gitignore
primer/Makefile
primer/primer.cabal

This series of commits makes the necessary & sufficient changes to build the `primer` and `primer-api` packages using GHC 9.6's WebAssembly target, and to get their tests to pass using the `wasmtime` runtime. We expect these are the only 2 libraries we'll need in order to run Primer in the student's browser, as everything else is either very database or HTTP API-specific.
There are a few hacks needed to make this work, but nothing that's particularly objectionable. The main thing I would like to clean up are the 4 additional `source-repository-package` overrides we need for upstream Wasm-related fixes, but presumably those will come over time.
There are currently 3 other major limitations:
1. Neither `haskell.nix` or `nixpkgs.haskellPackages` support the `wasm32-wasi` cross target at the …

`wasm32-wasi` support

---

primer-api/src/Primer/API.hs
primer-api/src/Primer/API/EdgeFlavor.hs
primer-api/src/Primer/API/NodeFlavor.hs
primer-api/test/outputs/APITree/Expr
primer-api/test/outputs/APITree/Type
primer-service/test/outputs/OpenAPI/openapi.json

~~Proof-of-concept. Doing this properly will require having `ID`s for binding nodes. We should probably just fully embrace #75. See also #93.~~ We've decided that we're happy to merge this without having proper IDs.
(frontend companion PR coming soon with fuller explanation)

Output separate nodes for variable bindings

---

cabal.project

This fixes an issue where Nix caching was significantly degraded in the default Nix shell, due to haskell.nix not being able to build `source-repository-package`s using Nix in Nix shells. We'd prefer not to do this, because it means that our Wasm dependencies are ever so slightly different than our native target dependencies, but at the moment the differences should be small enough not to matter.

fix: make Wasm upstream overrides dependent on `arch(wasm32)`

---

primer-api/src/Primer/API.hs
primer-benchmark/src/Benchmarks.hs
primer/gen/Primer/Gen/Core/Typed.hs
primer/primer.cabal
primer/src/Primer/App.hs
primer/src/Primer/Core.hs
primer/src/Primer/Core/Type/Utils.hs
primer/src/Primer/Core/Utils.hs
primer/src/Primer/EvalFullInterp.hs
primer/src/Primer/EvalFullStep.hs
primer/test/Tests/Action/Available.hs
primer/test/Tests/AlphaEquality.hs
primer/test/Tests/Eval/Utils.hs
primer/test/Tests/EvalFull.hs
primer/test/Tests/EvalFullInterp.hs
primer/test/Tests/EvalFullStep.hs
primer/test/Tests/Prelude/Polymorphism.hs
primer/test/Tests/Prelude/Utils.hs
primer/test/Tests/Shadowing.hs
primer/test/Tests/Typecheck.hs
primer/testlib/Primer/Test/TestM.hs

The one feature of the old stepwise evaluator that we don't replicate is the ability not to evaluate under lambdas.
This may be annoying if this new interpreter is hooked up to a frontend, as then any evaluation of a recursive function will diverge, even if an evaluation of that same function applied to an argument may succeed. The possible mitigations for this include
- only use this new interpreter for things of "base" type, i.e. things which have a type such that we expect them not to contain un-applied lambdas (note that if they contain holes, this expectation may be false, so a refinement would be "base type and not contain holes"). This is not quite "not an arrow/forall type", as we need to detect things like `Maybe (Bool -> Char)`, or a return type of `T` where `data T = C (Bool -> …

feat: interpreter (faster evaluator-to-normal-form)

---

cabal.project

As Wasm is an execute-only target, it makes sense to always build it
with `-O2`, including deps.
Fixes https://github.com/hackworthltd/primer/issues/1196

chore: always build `wasm32` targets with `-O2`

---

.buildkite/pipeline.yaml

We now have macOS Buildkite agents in the `nix-build` queue, so that we can cache macOS Nix shells, but we don't want these agents to build jobs generated by the Nix Buildkite plugin, as those need to go through our Linux builders due to the way Nix remote builds and caching work.

ci: ensure Nix Buildkite plugin jobs are built on Linux builders

---

.buildkite/primer-wasm.yaml

The Wasm tests are very expensive, and our build system isn't smart enough to know when they don't need to be re-run, so for now, we only run the tests once a PR hits the merge queue.

ci: only run Wasm tests once a PR reaches the merge queue

---

cabal.project

However, it hasn't been updated on Hackage yet, so we still need to resort to a `source-repository-package` for now.

chore(hackage): upstream `semirings` supports Wasm now

---

primer/primer.cabal
primer/test/Tests/EvalFullInterp.hs
primer/test/Tests/EvalFullStep.hs
primer/testlib/Primer/Test/Eval.hs

We refactor many of the interpreter and step evaluator full evaluation tests by moving the programs we want to evaluate into `primer-testlib`. Note that not all tests are amenable to this refactoring: some are too implementation-specific, and some are so simple that a refactoring wouldn't buy us much.
We could do some additional DRY by creating a test monad that abstracts away the differences between the two evaluation implementations, and then rewriting most of the tests to use this abstracted test framework. However, it's not clear whether it would be worth the effort, as it would be a fairly significant amount of work and would largely exchange boilerplate for boilerplate.
Note that this commit is intended to be a pure refactoring: no functional changes have been made to the tests, nor …

refactor: do some DRY for full eval tests

---

primer-api/src/Primer/API.hs

Prior to this change, we ran API-requested evaluations inside a transaction in STM (via `QueryApp` inside `withSession'`). However, in retrospect, this is (as far as I can determine) completely unnecessary:
* Evaluations can take a relatively long time, and could theoretically be restarted if their transaction is aborted; e.g., due to a concurrent edit.
* But we don't really care if an edit is made during an evaluation. All we need to do is guarantee that the `App` the evaluation is using is not modified during the evaluation.
We can guard against concurrent edits on the `App` used by an evaluation by atomically getting the `App` via STM, returning that app to the API handler for the evaluation request, and then simply running the evaluation on that (immutable) copy of the `App` outside …

feat(primer-api): run evaluation requests outside STM

---

primer-api/primer-api.cabal
primer-api/src/Primer/API.hs
primer-api/test/Tests/API.hs
primer-service/primer-service.cabal
primer-service/src/Primer/Client.hs
primer-service/src/Primer/OpenAPI.hs
primer-service/src/Primer/Servant/API.hs
primer-service/src/Primer/Servant/OpenAPI.hs
primer-service/src/Primer/Server.hs
primer-service/test/Tests/OpenAPI.hs
primer-service/test/outputs/OpenAPI/openapi.json
primer/src/Primer/App.hs
primer/src/Primer/EvalFullInterp.hs
primer/src/Primer/Examples.hs
primer/test/Tests/Action/Available.hs
primer/test/Tests/EvalFullInterp.hs
primer/test/Tests/EvalFullStep.hs
primer/test/Tests/Undo.hs
primer/testlib/Primer/Test/App.hs
primer/testlib/Primer/Test/Eval.hs

Note that we only expose the time-bounded interpreter via the HTTP API, because the non-bounded variant would enable trivial DoS attacks against a Primer service. We do, however, expose the non-bounded variant via the local API, as it might be useful to handle the various exceptions it can throw (and runaway evaluations) in an application-specific way, differently to how the time-bounded variant does it.
Closes https://github.com/hackworthltd/primer/issues/1239.
Note that there's currently a bug in the interpreter that prevents it from reducing top-level definitions that contain applications. See https://github.com/hackworthltd/primer/issues/1247.

feat: expose the interpreter via the various APIs

---

cabal.project
docs/haskell-style-guide.md
flake.lock
flake.nix
primer-api/primer-api.cabal
primer-benchmark/primer-benchmark.cabal
primer-selda/primer-selda.cabal
primer-service/primer-service.cabal
primer/primer.cabal

Note that Protolude upstream doesn't support GHC 9.10, so we use a (hopefully temporary) fork.

chore: upgrade to GHC 9.10.1

---

cabal.project

Just something I noticed in passing. Perhaps this syntax wasn't valid when the config was first written.

Collapse `source-repository-package` sections for `selda`

---

cabal.project
flake.nix
primer-service/primer-service.cabal

Setting `allow-newer: all` is finally catching up to us, so we go back to a more strict policy, and override only what's necessary (mainly due to a few packages not explicitly supporting GHC 9.10 yet).
Also, we bump servant & friends to the latest version.

chore(hackage): bump `index-state`, more strict PvP

---

.buildkite/primer-wasm.yaml
cabal.project
flake.lock
flake.nix

Namely:
* Bump `ghc-wasm` flake to latest, which includes support for Template
Haskell and macOS. Note that we now need to pass
`-fno-external-interpreter` to GHC; this appears to be related to
https://github.com/NixOS/nixpkgs/issues/275304.
* Run the Wasm build on macOS in CI, in addition to Linux.
* Don't bother building Haddocks in the Wasm build.
* Don't use `-fwrite-ide-info` in Wasm build.
* `allow-newer` for `time` package.

chore: improved Wasm support

---

cabal.project
flake.lock
primer-api/primer-api.cabal
primer-service/primer-service.cabal
primer/primer.cabal

Also, bump minimum version of `pretty-simple` to `4.1.3.0` and remove our Wasm workaround repo (which no longer exists).

chore: bump Nix dependencies and `index-state`

---

.hlint.yaml
Makefile
Makefile.wasm32
cabal.project
docs/developing.md
docs/wasm.md
flake.nix
makefiles/common.mk
primer-api/Makefile.wasm32
primer-miso/.gitignore
primer-miso/COPYING
primer-miso/Makefile
primer-miso/Makefile.wasm32
primer-miso/build-frontend.sh
primer-miso/exe/Main.hs
primer-miso/frontend/index.html
primer-miso/frontend/index.js
primer-miso/primer-miso.cabal
primer-miso/src/Primer/Miso.hs
primer-miso/src/Primer/Miso/Colors.hs
primer-miso/src/Primer/Miso/Layout.hs
primer-miso/src/Primer/Miso/Util.hs
primer/Makefile.wasm32
primer/src/Foreword.hs

This PR is a proof-of-concept re-implementation of our TypeScript- & React-based Primer frontend application in Haskell, using [Miso](https://haskell-miso.org) and GHC's Wasm backend. The goal of this PR is the following:
* Render an arbitrary Primer term definition (we've chosen polymorphic `map` here) as a tree, completely in the browser, with no backend service required.
* Upon selecting an arbitrary subexpression of the definition, render the subexpression's type as a tree alongside the definition's tree.
* Use as little JavaScript/TypeScript as possible.
* Make a best-effort attempt to mimic the CSS styling of the TypeScript/React implementation. (Notably, we have not yet implemented the "tidy trees" algorithm, nor have we made any attempt to render pattern matches left-to-right as …

feat: add `primer-miso`, an attempt to re-implement Primer's UI in Haskell

---

Makefile
flake.nix
primer-miso/Makefile
primer-miso/exe/Main.hs

@dhess Can you let me know whether `make develop-frontend` works for you? I think I've solved all the issues from https://github.com/hackworthltd/primer/pull/1304#discussion_r1861223840, but I haven't tested on MacOS.

Improve development workflow (`ghcid` with `jsaddle-warp`)

---

cabal.project
flake.lock
flake.nix
primer-miso/primer-miso.cabal

Note that this also bumps `primer-miso` to the latest (1.8.7.0). 
We did have to un-pin `experimental` and `jsaddle-wasm` to get this working, however. Hopefully that's temporary until we have proper upstream GHC Wasm releases.

chore: un-pin ghc-wasm-meta and fix `primer-miso`

---

.buildkite/primer-wasm.yaml
flake.lock

The version of `wizer` pulled in by this updated `ghc-wasm` flake supports tail calls, which we now need.
(This `ghc-wasm` flake version breaks the Wasm build on macOS, or at least it does on macOS 15.4.1, but we'll just have to deal with the breakage for now, as the need for the updated `wizer` overrides a working macOS build.

fix: bump `ghc-wasm` flake to fix `wizer`

---

primer-miso/src/Primer/Miso.hs
primer-miso/src/Primer/Miso/Util.hs

I noticed that rendering performance was surprisingly slow with large trees, and that it scaled linearly with the number of `class_` attributes (around 1ms each).
The first commit is really a leftover from a first attempt at solving it. Unfortunately there was no noticeable impact on performance, even with Miso bumped to a version which uses `JSString` on Wasm instead of `Text`. But there's no harm in keeping it around now that the work has been done. It will be required eventually, and would probably become difficult to merge if left on a separate branch.
The second commit actually solves the problem. I'm still investigating exactly why Miso is so slow without this fix.

Improve Miso string performance

---

primer-miso/src/Primer/Miso.hs

Brings back a useful feature we had in the old React frontend.
This is based on #1347 for now, since there'd be conflicts otherwise.

Add option to render node IDs in frontend for debugging

---

primer-miso/frontend/style.css
primer-miso/primer-miso.cabal
primer-miso/src/Primer/Miso.hs
primer-miso/src/Primer/Miso/Util.hs
primer/src/Primer/Eval.hs
primer/src/Primer/Eval/NormalOrder.hs

As mentioned in the last commit message, this is still kind of proof-of-concept, but it works rather well.
And even with less-than-perfect UX, it feels great to be able to explore eval steps again, seeing as we never got this far with the JS frontend. This brings back a key Primer feature which we effectively haven't had for three and a half years!

Interactive eval

---

primer-miso/frontend/style.css
primer-miso/src/Primer/Miso.hs
primer-miso/src/Primer/Miso/Util.hs
primer/src/Primer/Action.hs
primer/src/Primer/Action/ProgAction.hs
primer/src/Primer/Action/ProgError.hs
primer/src/Primer/App.hs
primer/src/Primer/App/Base.hs

After #1351, ~~which this is based on top of,~~ this is the final major feature for the new frontend. We can now build any program!
UI is again proof-of-concept, but I don't expect to make major changes there for now. In fact, I think that while it's hardly intuitive in its current form (better labels would help for a start, but this is true for much of the current UI), this is the direction we should be heading in. The choice we've made to only show one definition at a time frees us from worrying about showing the whole type definition as connected, which was always a bit weird in the React frontend. So we now get back some of the clarity of the form-based UI we had in our PureScript frontend, but with the ability to actually create arbitrarily-complex type defs (the fully form-based …

Add UI for editing type definitions

---

.buildkite/pipeline.yaml

This version skips the evaluation of cached derivations.

ci: use Nix Buildkite plugin `v2.1.0`
